apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.org/server-snippets: |
        resolver kube-dns.kube-system valid=10s;
        location = /mirror {
            internal;
            set $shadow_service_name "hello-shadow-service";
            proxy_set_header X-Mirror-Request  true;
            proxy_set_header X-Shadow-Service  $shadow_service_name;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header Host  $host;
            proxy_pass http://hello-shadow-service$request_uri;
        }
    nginx.org/location-snippets: |
        mirror  /mirror;
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: hello-app-service
            servicePort: 80
